# Generated by Django 6.0.1 on 2026-01-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
