# Generated by Django 6.0.1 on 2026-01-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_person_email_person_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
